name: Build and Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest
    
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: File Organizer v1.0.1
          tag_name: v1.0.1
          files: dist-exe/*.exe
          body: "¡Nueva versión con opciones de configuración (Arrancar al inicio y Siempre encima)!"
